kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager
  namespace: monitoring
data:
  config.yml: |-
    global:
       smtp_smarthost: 'smtp.139.com:25'
       smtp_from: 'xxxxxx@139.com'
       smtp_auth_username: 'xxxxxx@139.com'
       smtp_auth_password: 'xxxxxx'
       smtp_require_tls: false
                                
    route:
      group_by: ['instance']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 7m
      receiver: email
      routes:
      - match:
          severity: page
          receiver: email
    
    receivers:
    - name: 'email'
      email_configs:
      - to: 'xxxxxx@qq.com'
